### PR TITLE
ignored-routes

### PR DESCRIPTION
**Pull request by jochensengier**
As discussed in #149, this PR will add a new feature/config to exclude certain routes from localization.

Can you have a look please?

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Thanks for the PR :+1:

**Comment by jochensengier** [comment]
Thank you for allowing this feature!
Perhaps the documentation should also be updated?

**Comment by arcanedev-maroc** [comment]
Yes, i'm already making some changes: #153

**Comment by arcanedev-maroc** [comment]
Released as `v6.3.0`

**Pull request merged**
